[package]
name = "cloudtiles"
version = "0.1.0"
edition = "2021"

[profile.dev]
debug = true
opt-level = 3

[profile.release]
debug = false
lto = false
opt-level = 3
overflow-checks = false
strip = true

[dependencies]
brotli = "3.3.4"
bytes = "1.3.0"
clap = { version = "4.0.29", features = ["derive"] }
flate2 = "1.0.25"
indicatif = "0.17.2"
r2d2 = "0.8.10"
r2d2_sqlite = "0.21.0"
rayon = "1.6.1"
rusqlite = "0.28.0"
serde_json = "1.0.89"
tar = "0.4.38"
