[package]
name = "versatiles"
edition = "2021"
version = "0.10.1"
description = "A toolbox for converting, checking and serving map tiles in various formats."
homepage = "https://versatiles.org"
repository = "https://github.com/versatiles-org/versatiles-rs"
authors = ["Michael Kreil <versatiles@michael-kreil.de>"]
keywords = ["versatiles", "mbtiles", "tiles", "map"]
categories = ["command-line-utilities", "science::geo", "web-programming::http-server"]
readme = "README.md"
license = "MIT"
exclude = [
	".githooks/",
	".github/",
	".gitignore",
	".prettierignore",
	".vscode/",
	"/docker",
	"/helpers",
	"/testdata",
]
metadata.deb.maintainer = "Michael Kreil <versatiles@michael-kreil.de>"

[profile.dev]
opt-level = 1
debug = true
rpath = false
lto = false
debug-assertions = true
panic = "unwind"
incremental = true
overflow-checks = true

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = true
debug-assertions = true
codegen-units = 1
panic = "unwind"
incremental = false
overflow-checks = false
strip = true

[[bin]]
name = "versatiles"
path = "src/main.rs"
required-features = ["cli"]

[lib]
name = "versatiles"
path = "src/lib.rs"

[dependencies]
anyhow = { version = "1.0.86", default-features = false, features = ["std", "backtrace"] }
async-trait = { version = "0.1.80", default-features = false }
axum = { version = "0.7.5", default-features = false, optional = true, features = [
	"http1",
	"http2",
	"tokio",
] }
brotli = { version = "6.0.0", default-features = false, features = ["std"] }
byteorder = { version = "1.5.0", default-features = false, features = ["std"] }
bytes = { version = "1.6.0", default-features = false }
clap = { version = "4.5.4", optional = true, features = ["wrap_help"] }
clap-verbosity-flag = { version = "2.2.0", default-features = false, optional = true }
colored = { version = "2.1.0", default-features = false, optional = true }
csv = "1.3.0"
enumset = { version = "1.1.3", default-features = false }
env_logger = { version = "0.11.3", default-features = false, optional = true }
flate2 = { version = "1.0.30", default-features = false, features = ["default"] }
futures-util = { version = "0.3.30", default-features = false, features = ["std"] }
hyper = { version = "1.3.1", default-features = false, optional = true, features = ["http2"] }
image = { version = "0.25.1", default-features = false, optional = true, features = [
	"jpeg",
	"png",
] }
itertools = { version = "0.13.0", default-features = false, features = ["use_alloc"] }
lazy_static = { version = "1.4.0", optional = true }
log = { version = "0.4.21", default-features = false }
mime_guess = { version = "2.0.4", default-features = false, optional = true }
num_cpus = { version = "1.16.0", default-features = false }
r2d2 = { version = "0.8.10", default-features = false, optional = true }
r2d2_sqlite = { version = "0.24.0", default-features = false, optional = true, features = [
	"bundled",
] }
regex = { version = "1.10.4", default-features = false, optional = true, features = ["unicode"] }
reqwest = { version = "0.12.4", default-features = false, optional = true, features = [
	"rustls-tls",
] }
tar = { version = "0.4.40", default-features = false, optional = true }
terminal_size = { version = "0.3.0", default-features = false, optional = true }
tokio = { version = "1.37.0", default-features = false, features = ["rt-multi-thread", "sync"] }
webp = { version = "0.3.0", default-features = false, optional = true, features = ["img"] }
yaml-rust2 = { version = "0.8.0", default-features = false, optional = true }

[dev-dependencies]
assert_fs = "1.1.1"
lazy_static = "1.4.0"
wildmatch = "2.3.3"
tokio = { version = "1.37.0", default-features = false, features = [
	"macros",
	"rt-multi-thread",
	"sync",
] }

[features]
default = ["full", "cli"]
cli = [
	"dep:axum",
	"dep:clap-verbosity-flag",
	"dep:clap",
	"dep:env_logger",
	"dep:hyper",
	"dep:mime_guess",
	"dep:tar",
	"full",
]
full = [
	"dep:colored",
	"dep:hyper",
	"dep:image",
	"dep:lazy_static",
	"dep:r2d2_sqlite",
	"dep:r2d2",
	"dep:tar",
	"dep:terminal_size",
	"dep:webp",
	"dep:yaml-rust2",
	"http",
]
http = ["dep:lazy_static", "dep:regex", "dep:reqwest"]
