[package]
name = "opencloudtiles"
version = "0.1.2"
edition = "2021"
authors = ["Michael Kreil"]
description = "A toolbox for converting, checking and serving map tiles in various formats."
readme = "readme.md"
homepage = "https://www.opencloudtiles.org"
repository = "https://github.com/OpenCloudTiles/opencloudtiles-tools"
license = "MIT"
exclude = ["**/.DS_Store", ".DS_Store"]

[profile.dev]
codegen-units = 256
debug = true
debug-assertions = true
incremental = true
lto = false
opt-level = 1
overflow-checks = true
panic = 'unwind'
rpath = false

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = 3
overflow-checks = false
panic = 'unwind'
rpath = false
strip = true  # Automatically strip symbols from the binary.

[dependencies]
brotli = "3.3.4"
byteorder = "1.4.3"
clap = { version = "4.0.32", features = ["derive"] }
enumset = "1.0.12"
flate2 = "1.0.25"
hyper = { version = "0.14", features = ["full"] }
image = "0.24.5"
indicatif = "0.17.2"
itertools = "0.10.5"
mime_guess = "2.0.4"
r2d2 = "0.8.10"
r2d2_sqlite = "0.21.0"
rayon = "1.6.1"
rusqlite = "0.28.0"
serde_json = "1.0.91"
tar = "0.4.38"
tokio = { version = "1.23.1", features = ["full"] }
url = "2.3.1"
webp = "0.2.2"
