[package]
name = "opencloudtiles"
edition = "2021"
version = "0.1.4"
authors = ["Michael Kreil"]
description = "A toolbox for converting, checking and serving map tiles in various formats."
homepage = "https://www.opencloudtiles.org"
readme = "readme.md"
license = "MIT"
repository = "https://github.com/OpenCloudTiles/opencloudtiles-tools"

[profile.dev]
opt-level = 1
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 256
panic = "unwind"
incremental = true
overflow-checks = true

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = "unwind"
incremental = false
overflow-checks = false
strip = true

[dependencies]
brotli = { version = "3.3.4", default-features = false, features = ["std"] }
byteorder = { version = "1.4.3", default-features = false, features = [] }
clap = { version = "4.0.32", default-features = false, features = [] }
clap-verbosity-flag = { version = "2.0.0", default-features = false, features = [] }
enumset = { version = "1.0.12", default-features = false, features = [] }
env_logger = { version = "0.10.0", default-features = false, features = [] }
flate2 = { version = "1.0.25", default-features = false, features = ["miniz_oxide"] }
futures = { version = "0.3.25", default-features = false, features = [] }
hyper = { version = "0.14.23", default-features = false, features = ["server"] }
image = { version = "0.24.5", default-features = false, features = ["jpeg", "png"] }
indicatif = { version = "0.17.2", default-features = false, features = [] }
itertools = { version = "0.10.5", default-features = false, features = [] }
log = { version = "0.4.17", default-features = false, features = [] }
mime_guess = { version = "2.0.4", default-features = false, features = [] }
object_store = { version = "0.5.3", default-features = false, features = ["gcp"] }
r2d2 = { version = "0.8.10", default-features = false, features = [] }
r2d2_sqlite = { version = "0.21.0", default-features = false, features = [] }
rayon = { version = "1.6.1", default-features = false, features = [] }
rusqlite = { version = "0.28.0", default-features = false, features = [] }
tar = { version = "0.4.38", default-features = false, features = [] }
tokio = { version = "1.24.1", default-features = false, features = ["rt-multi-thread"] }
urlencoding = { version = "2.1.2", default-features = false, features = [] }
webp = { version = "0.2.2", default-features = false, features = ["img"] }
