[package]
name = "cloudtiles"
version = "0.1.0"
edition = "2021"

[profile.dev]
debug = true
opt-level = 3

[profile.release]
debug = false
lto = false
opt-level = 3
overflow-checks = false
strip = true

[dependencies]
brotli = "3.3.4"
clap = "4.0.29"
flate2 = "1.0.25"
rusqlite = "0.28.0"
serde_json = "1.0.89"
