[package]
name = "versatiles"
edition = "2021"
version = "0.2.14"
description = "A toolbox for converting, checking and serving map tiles in various formats."
homepage = "https://versatiles.org"
repository = "https://github.com/versatiles-org/versatiles"
authors = ["Michael Kreil <versatiles@michael-kreil.de>"]
keywords = ["versatiles", "mbtiles", "tiles", "map"]
categories = ["command-line-utilities", "science::geo", "web-programming::http-server"]
readme = "readme.md"
license = "MIT"
exclude = ["benches/resources/*"]

[workspace]
members = [ "libs/versatiles_container",  "libs/versatiles_server",  "libs/versatiles_shared" ]

[profile.dev]
opt-level = 1
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 256
panic = "unwind"
incremental = true
overflow-checks = true

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = "unwind"
incremental = false
overflow-checks = false
strip = true

[profile.bench]
lto = false

[dependencies]
versatiles_container = { path = "libs/versatiles_container" }
versatiles_shared = { path = "libs/versatiles_shared" }
versatiles_server = { path = "libs/versatiles_server" }
clap = { version = "4.1.10", default-features = true }
clap-verbosity-flag = { version = "2.0.0", default-features = true }
env_logger = { version = "0.10.0", default-features = false, features = ["regex"] }
futures = { version = "0.3.27", default-features = false, features = ["executor"] }
log = { version = "0.4.17", default-features = false }
regex = { version = "1.7.1", default-features = false }
tokio = { version = "1.26.0", default-features = false, features = ["macros"] }

[dev-dependencies]
criterion = { version = "0.4.0", default-features = false }
rand = { version = "0.8.5", default-features = true }
reqwest = { version = "0.11.14", default-features = false, features=["blocking"] }

[[bench]]
name = "main"
harness = false
