[workspace]
members = ["versatiles", "versatiles_core", "versatiles_derive", "versatiles_geometry"]
default-members = ["versatiles", "versatiles_core", "versatiles_derive", "versatiles_geometry"]
resolver = "2"

[workspace.package]
authors = ["Michael Kreil <versatiles@michael-kreil.de>"]
categories = ["command-line-utilities", "science::geo", "web-programming::http-server"]
description = "A toolbox for converting, checking and serving map tiles in various formats."
edition = "2021"
homepage = "https://versatiles.org"
keywords = ["versatiles", "mbtiles", "tiles", "map"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/versatiles-org/versatiles-rs"
version = "0.11.2"
exclude = [
	".githooks/",
	".github/",
	".gitignore",
	".prettierignore",
	".vscode/",
	"/docker",
	"/helpers",
	"/testdata",
]

[profile.dev]
opt-level = 1
debug = true
rpath = false
lto = false
debug-assertions = true
panic = "unwind"
incremental = true
overflow-checks = true

[profile.test]
opt-level = 1
lto = false
incremental = true

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = true
debug-assertions = true
codegen-units = 1
panic = "unwind"
incremental = false
overflow-checks = false
strip = true

[workspace.dependencies]
anyhow = { version = "1.0.86", default-features = false, features = ["std"] }
assert_fs = { version = "1.1.1", default-features = false }
async-trait = { version = "0.1.80", default-features = false }
axum = { version = "0.7.5", default-features = false }
brotli = { version = "6.0.0", default-features = false }
byteorder = { version = "1.5.0", default-features = false, features = ["std"] }
bytes = { version = "1.6.0", default-features = false }
clap = { version = "4.5.4", default-features = false, features = ["std"] }
clap-verbosity-flag = { version = "2.2.0", default-features = false }
colored = { version = "2.1.0", default-features = false }
csv = { version = "1.3.0", default-features = false }
enumset = { version = "1.1.3", default-features = false }
env_logger = { version = "0.11.3", default-features = false }
flate2 = { version = "1.0.30", default-features = false }
futures = { version = "0.3.30", default-features = false }
hyper = { version = "1.3.1", default-features = false }
image = { version = "0.25.1", default-features = false }
itertools = { version = "0.13.0", default-features = false }
lazy_static = { version = "1.4.0", default-features = false }
log = { version = "0.4.21", default-features = false }
mime_guess = { version = "2.0.4", default-features = false }
num_cpus = { version = "1.16.0", default-features = false }
proc-macro2 = { version = "1.0.84", default-features = false }
quote = { version = "1.0.36", default-features = false }
r2d2 = { version = "0.8.10", default-features = false }
r2d2_sqlite = { version = "0.24.0", default-features = false }
regex = { version = "1.10.4", default-features = false }
reqwest = { version = "0.12.4", default-features = false }
syn = { version = "2.0.66", default-features = false }
tar = { version = "0.4.40", default-features = false }
terminal_size = { version = "0.3.0", default-features = false }
tokio = { version = "1.37.0", default-features = false }
webp = { version = "0.3.0", default-features = false }
wildmatch = { version = "2.3.4", default-features = false }
yaml-rust2 = { version = "0.8.0", default-features = false }

versatiles_core = { version = "0", path = "versatiles_core" }
versatiles_derive = { version = "0", path = "versatiles_derive" }
versatiles_geometry = { version = "0", path = "versatiles_geometry" }
