[package]
name = "opencloudtiles"
edition = "2021"
version = "0.1.4"
authors = ["Michael Kreil"]
description = "A toolbox for converting, checking and serving map tiles in various formats."
homepage = "https://www.opencloudtiles.org"
readme = "readme.md"
license = "MIT"
repository = "https://github.com/OpenCloudTiles/opencloudtiles-tools"

[profile.dev]
opt-level = 1
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 256
panic = "unwind"
incremental = true
overflow-checks = true

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = "unwind"
incremental = false
overflow-checks = false
strip = true
