[package]
name = "versatiles"
edition = "2021"
version = "0.2.14"
description = "A toolbox for converting, checking and serving map tiles in various formats."
homepage = "https://versatiles.org"
repository = "https://github.com/versatiles-org/versatiles-rs"
authors = ["Michael Kreil <versatiles@michael-kreil.de>"]
keywords = ["versatiles", "mbtiles", "tiles", "map"]
categories = ["command-line-utilities", "science::geo", "web-programming::http-server"]
readme = "README.MD"
license = "MIT"
exclude = ["ressources/*"]

[dependencies]
async-trait = { version = "0.1.68", default-features = false }
axum = { version = "0.6.11", default-features = false, features = ["tokio"] }
brotli = { version = "3.3.4", default-features = false, features = ["std"] }
byteorder = { version = "1.4.3", default-features = false }
bytes = { version = "1.4.0", default-features = false }
clap = { version = "4.2.1", default-features = true }
clap-verbosity-flag = { version = "2.0.0", default-features = true }
enumset = { version = "1.0.12", default-features = false }
env_logger = { version = "0.10.0", default-features = false, features = ["regex"] }
flate2 = { version = "1.0.25", default-features = false }
futures = { version = "0.3.27", default-features = false, features = ["executor"] }
hyper = { version = "0.14.25", default-features = false }
image = { version = "0.24.6", default-features = false, features = ["jpeg", "png"] }
itertools = { version = "0.10.5", default-features = false, features = ["use_alloc"] }
log = { version = "0.4.17", default-features = false }
mime_guess = { version = "2.0.4", default-features = false }
rayon = { version = "1.7.0", default-features = false }
regex = { version = "1.7.2", default-features = false }
reqwest = { version = "0.11.16", features=["blocking", "rustls-tls"] }
rusqlite = { version = "0.29.0", default-features = false }
tar = { version = "0.4.38", default-features = false }
term_size = { version = "0.3.2", default-features = false }
tokio = { version = "1.27.0", default-features = false, features = ["macros"] }
webp = { version = "0.2.2", default-features = false, features = ["img"] }

[dev-dependencies]
assert_fs = { version = "1.0.12" }
criterion = { version = "0.4.0", default-features = false }
rand = { version = "0.8.5", default-features = true }

[[bin]]
name = "versatiles"
path = "src/main.rs"

[[bench]]
name = "main"
harness = false
path = "benches/lib.rs"

[profile.dev]
opt-level = 1
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 256
panic = "unwind"
incremental = true
overflow-checks = true

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = "unwind"
incremental = false
overflow-checks = false
strip = true

[profile.bench]
lto = false
