[package]
name = "versatiles"
edition = "2021"
version = "0.5.9"
description = "A toolbox for converting, checking and serving map tiles in various formats."
homepage = "https://versatiles.org"
repository = "https://github.com/versatiles-org/versatiles-rs"
authors = ["Michael Kreil <versatiles@michael-kreil.de>"]
keywords = ["versatiles", "mbtiles", "tiles", "map"]
categories = ["command-line-utilities", "science::geo", "web-programming::http-server"]
readme = "README.MD"
license = "MIT"
exclude = [
	".githooks/",
	".github/",
	".gitignore",
	".prettierignore",
	".vscode/",
	"/docker",
	"/helpers",
	"/testdata"
]

[dependencies]
async-stream = { version = "0.3.5", default-features = false }
async-trait = { version = "0.1.73", default-features = false }
axum = { version = "0.6.20", default-features = false, optional = true, features = ["tokio"] }
brotli = { version = "3.3.4", default-features = false, features = ["std"] }
byteorder = { version = "1.4.3", default-features = true }
bytes = { version = "1.4.0", default-features = false }
clap = { version = "4.4.2", default-features = true, optional = true, features = ["wrap_help"] }
clap-verbosity-flag = { version = "2.0.1", default-features = false, optional = true }
enumset = { version = "1.1.2", default-features = false }
env_logger = { version = "0.10.0", default-features = true, optional = true }
flate2 = { version = "1.0.27", default-features = true }
futures-util = { version = "0.3.28", default-features = false }
hyper = { version = "0.14.27", default-features = false, optional = true, features = ["http2", "tcp"] }
image = { version = "0.24.7", default-features = false, optional = true, features = ["jpeg", "png"] }
itertools = { version = "0.11.0", default-features = false, features = ["use_alloc"] }
lazy_static = { version = "1.4.0", default-features = false, optional = true }
log = { version = "0.4.20", default-features = false }
mime_guess = { version = "2.0.4", default-features = false, optional = true }
r2d2 = { version = "0.8.10", default-features = false, optional = true }
r2d2_sqlite = { version = "0.22.0", default-features = false, optional = true, features=["bundled"] }
regex = { version = "1.9.4", default-features = true, optional = true }
reqwest = { version = "0.11.20", default-features = false, optional = true, features=["rustls-tls"] }
tar = { version = "0.4.40", default-features = false, optional = true }
term_size = { version = "0.3.2", default-features = false }
tokio = { version = "1.32.0", default-features = false, features = ["macros", "rt-multi-thread", "sync"] }
webp = { version = "0.2.5", default-features = false, optional = true, features = ["img"] }

[dev-dependencies]
assert_fs = { version = "1.0.13" }
criterion = { version = "0.5.1", default-features = false, features = ["async_futures"] }

[features]
default = ["full"]
full = ["cli", "image", "mbtiles", "request", "server", "tar"]
cli = ["dep:clap", "dep:clap-verbosity-flag", "dep:env_logger"]
image = ["dep:image", "dep:webp"]
mbtiles = ["dep:r2d2", "dep:r2d2_sqlite"]
request = ["dep:lazy_static", "dep:regex", "dep:reqwest"]
server = ["dep:axum", "dep:hyper", "dep:mime_guess", "dep:regex"]
tar = ["dep:tar"]

[lib]
name = "versatiles"
path = "src/lib.rs"

[[bin]]
name = "versatiles"
path = "src/main.rs"
required-features = ["cli"]

[profile.dev]
opt-level = 1
debug = true
rpath = false
lto = false
debug-assertions = true
panic = "unwind"
incremental = true
overflow-checks = true

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = "unwind"
incremental = false
overflow-checks = false
strip = true
