[package]
name = "versatiles_core"
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
brotli = { version = "6.0.0", default-features = false, features = ["std"] }
byteorder = { workspace = true, features = [] }
clap = { workspace = true, optional = true, features = ["std", "derive"] }
colored = { version = "2.1.0", default-features = false, optional = true }
enumset.workspace = true
flate2 = { version = "1.0.30", default-features = false, features = ["default"] }
futures = { workspace = true, features = ["default"] }
indicatif = { version = "0.17.8", default-features = false, features = [
	"unicode-width",
], optional = true }
itertools.workspace = true
lazy_static = { workspace = true }
num_cpus = { version = "1.16.0", default-features = false }
regex = { workspace = true, features = ["unicode-case", "unicode-perl"] }
reqwest = { workspace = true, features = ["rustls-tls"] }
tokio = { workspace = true, features = ["rt-multi-thread", "sync"] }

[dev-dependencies]
assert_fs.workspace = true
tokio = { workspace = true, features = ["macros"] }
wildmatch.workspace = true

versatiles.workspace = true

[features]
default = ["cli"]
cli = ["dep:clap", "dep:colored", "dep:indicatif"]
test = []
