[package]
name = "versatiles_core"
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
byteorder = { workspace = true, features = [] }
bytes.workspace = true
clap = { workspace = true, optional = true, features = ["std", "derive"] }
enumset.workspace = true
futures = { workspace = true, features = ["default"] }
indicatif = { version = "0.17.8", default-features = false, features = ["unicode-width"] }
itertools.workspace = true
lazy_static = { workspace = true, optional = true }
num_cpus = { version = "1.16.0", default-features = false }
regex = { workspace = true, optional = true, features = ["unicode-case", "unicode-perl"] }
reqwest = { workspace = true, optional = true, features = ["rustls-tls"] }
tokio = { workspace = true, features = ["rt-multi-thread", "sync"] }

[dev-dependencies]
assert_fs.workspace = true
tokio = { workspace = true, features = ["macros"] }
wildmatch.workspace = true

[features]
default = []
cli = ["dep:clap"]
http = ["dep:lazy_static", "dep:regex", "dep:reqwest"]
test = []
