[package]
name = "versatiles"
edition = "2021"
version = "0.7.3"
description = "A toolbox for converting, checking and serving map tiles in various formats."
homepage = "https://versatiles.org"
repository = "https://github.com/versatiles-org/versatiles-rs"
authors = ["Michael Kreil <versatiles@michael-kreil.de>"]
keywords = ["versatiles", "mbtiles", "tiles", "map"]
categories = ["command-line-utilities", "science::geo", "web-programming::http-server"]
readme = "README.md"
license = "MIT"
exclude = [
	".githooks/",
	".github/",
	".gitignore",
	".prettierignore",
	".vscode/",
	"/docker",
	"/helpers",
	"/testdata",
]

[package.metadata.deb]
maintainer = "Michael Kreil <versatiles@michael-kreil.de>"

[dependencies]
anyhow = { version = "1.0.83", features = ["std", "backtrace"] }
async-trait = { version = "0.1.80", default-features = false }
axum = { version = "0.7.5", default-features = false, features = ["tokio", "http1", "http2"] }
brotli = { version = "6.0.0", default-features = false, features = ["std"] }
byteorder = { version = "1.5.0" }
bytes = { version = "1.6.0", default-features = false }
clap = { version = "4.5.4", features = ["wrap_help"] }
clap-verbosity-flag = { version = "2.2.0", default-features = false }
colored = { version = "2.1.0", default-features = false }
enumset = { version = "1.1.3", default-features = false }
env_logger = { version = "0.11.3" }
flate2 = { version = "1.0.30" }
futures-util = { version = "0.3.30", default-features = false, features = ["std"] }
hyper = { version = "1.3.1", default-features = false, features = ["http2"] }
image = { version = "0.25.1", default-features = false, features = ["jpeg", "png"] }
itertools = { version = "0.12.1", default-features = false, features = ["use_alloc"] }
log = { version = "0.4.21", default-features = false }
mime_guess = { version = "2.0.4", default-features = false }
num_cpus = { version = "1.16.0", default-features = false }
r2d2 = { version = "0.8.10", default-features = false }
r2d2_sqlite = { version = "0.24.0", default-features = false, features = ["bundled"] }
regex = { version = "1.10.4" }
reqwest = { version = "0.12.4", default-features = false, features = ["rustls-tls"] }
tar = { version = "0.4.40", default-features = false }
terminal_size = { version = "0.3.0", default-features = false }
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread", "sync"] }
webp = { version = "0.3.0", default-features = false, features = ["img"] }
versatiles-lib = { path = "../versatiles-lib", version = "0.7.3", features = ["full"] }

[dev-dependencies]
assert_fs = { version = "1.1.1" }
lazy_static = { version = "1.4.0", default-features = false }
versatiles-lib = { path = "../versatiles-lib", version = "0.7.3", features = ["full", "mock"] }

[[bin]]
name = "versatiles"
path = "src/main.rs"
