---
name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
    - cron: '0 0 15 * *'
  workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    name: rustfmt
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with: {submodules: true}
    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal
        components: rustfmt, clippy
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Documentation
      run: cargo doc --workspace
    - name: Clippy
      run: cargo clippy --workspace -- -D warnings

  test_apt:
    name: test apt
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with: {submodules: false}

    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Build
      run: cargo build --verbose --workspace --exclude netcdf-src

    - name: Test
      run: cargo test --verbose --workspace --exclude netcdf-src
