name: Continuous Integration

on:
  push:
    branches:
      - "**"
    tags:
      - "!**" # Don't run twice on commits with tags
    paths-ignore:
      - ".github/workflows/**"
      - "**.Dockerfile"
      - "**.md"
  pull_request:
  schedule:
    - cron: "0 3 5,20 * *"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Init Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Cargo Fmt
        run: cargo fmt -- --check
      - name: Cargo Clippy
        run: cargo clippy -- -D warnings
      - name: Cargo Check
        run: cargo check
      - name: Test Features
        run: ./helpers/test_features.sh
      - name: Install Cargo Coverage
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Cargo Coverage
        run: cargo llvm-cov test --bin versatiles --tests --lcov --output-path ./lcov.info
      - name: Upload Coverage
        uses: codecov/codecov-action@v3
