name: release docker image
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      -
        name: Prepare
        run: echo "LATEST_VERSION=$(git tag | egrep "^v\d+\.\d+\.\d+$" | sort --version-sort | tail -n1)" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      -
#        name: Build and export to Docker
#        uses: docker/build-push-action@v4
#        with:
#          platforms: linux/amd64,linux/arm64
#          load: true
#          tags: ${{ env.TEST_TAG }}
#      -
#        name: Test
#        run: |
#          docker run --rm ${{ env.TEST_TAG }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64, linux/386
          push: true
          tags: versatiles/versatiles:latest, versatiles/versatiles:${{ env.LATEST_VERSION }}
