name: Upgrade Dependencies

on:
  schedule:
    - cron: '25 6 3,17 * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Init Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo-edit
        run: cargo install cargo-edit

      - name: Upgrade Dependencies
        run: cargo upgrade --incompatible

      - name: Update Dependencies
        run: cargo update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: 'build(deps): Upgrade Dependencies'
          title: 'Upgrade Dependencies'
